name: Docker Image CI

on:
  push:
    branches: ["main"]
env:
  AWS_REGION: "us-east-1"
  SITE_NAME: "portfolio"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install AWS CLI
          run: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - name: Upload index.html to S3
        run: |
          aws s3 cp public s3://${{ secrets.AWS_S3_BUCKET }}/${{ env.SITE_NAME }} --recursive